<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditTruck.aspx.cs" Inherits="GoodsDeliverySystem.Transportation.DeleteTruck" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col-md-8">
            <section id="deleteTruckForm">
                <div class="form-horizontal">
                    <br />
                    <br />
                    <div id="Error" runat="server" class="alert alert-danger" style="display: none;">
                        <strong>Warning: </strong>There was a problem deleting the truck.
                    </div>
                    <div id="Success" runat="server" class="alert alert-success" style="display: none;">
                        <strong>Successfully deleted truck.</strong>
                    </div>
                    <h3>Edit/Delete Truck</h3>
                    <div class="form-group">
                        <asp:Label ID="Label1" runat="server" AssociatedControlID="Search" CssClass="col-md-2 control-label">Search:</asp:Label>
                        <div class="col-md-10">
                            <asp:TextBox runat="server" ID="Search" CssClass="form-control" Text="" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <asp:GridView ID="gvTrucks" runat="server" AllowSorting="True" AutoGenerateDeleteButton="False"
                                AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="truckId"
                                DataSourceID="gdsDataSource1" CssClass="table table-bordered" AllowPaging="True" RowStyle-Wrap="false" EditRowStyle-Wrap="true">
                                <SelectedRowStyle BackColor="#CDCDEF" />
                                <AlternatingRowStyle BackColor="#EFEFEF" />
                                <Columns>
                                    <asp:BoundField DataField="truckId" HeaderText="ID" InsertVisible="false" ReadOnly="true" SortExpression="truckId" Visible="false" />
                                    <asp:TemplateField ShowHeader="False">
                                        <ItemTemplate>
                                            <asp:LinkButton ID="DeleteButton" runat="server" Text="Delete"
                                                CommandName="Delete" OnClientClick="return confirm('Are you sure you want to delete this truck?');"
                                                AlternateText="Delete" />
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="License Plate" SortExpression="licensePlateNum">
                                        <ItemTemplate>
                                            <asp:Label ID="lblLicensePlateNum" runat="server" Text='<%# Bind("licensePlateNum") %>'></asp:Label>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:TextBox ID="LicensePlateNum" runat="server" Text='<%# Bind("licensePlateNum") %>' Columns="8" MaxLength="8" />
                                            <asp:RequiredFieldValidator runat="server" ControlToValidate="LicensePlateNum" CssClass="text-danger" Text="This field is required" />
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="License Plate State" SortExpression="licensePlateState">
                                        <ItemTemplate>
                                            <asp:Label ID="lblLicensePlateState" runat='server' Text='<%# Bind("licensePlateState") %>' />
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:DropDownList runat="server" ID="LicensePlateState" Width="150px" CssClass="form-control" DataSourceID="SqlDataSource1" DataTextField="Name" DataValueField="Abbreviation" AppendDataBoundItems="true" SelectedValue='<%#Bind("licensePlateState")%>'>
                                            </asp:DropDownList>
                                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:GoodsDeliveryConnectionString %>" SelectCommand="SELECT * FROM [States] ORDER BY [Name]"></asp:SqlDataSource>
                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="LicensePlateState"
                                                CssClass="text-danger" ErrorMessage="This field is required" />
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField ConvertEmptyStringToNull="False" HeaderText="Length (inches)" SortExpression="length">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Length" runat="server" Text='<%# Bind("length") %>' Columns="8" MaxLength="8"></asp:TextBox>
                                            <asp:RegularExpressionValidator ID="lengthRegexValidator" runat="server" ControlToValidate="Length" CssClass="text-danger" Text="Length must be a decimal" ValidationExpression="\d+\.?\d*" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("length") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Width (inches)" SortExpression="width">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Width" runat="server" Text='<%# Bind("width") %>' Columns="8" MaxLength="8"></asp:TextBox>
                                            <asp:RegularExpressionValidator ID="widthRegex" runat="server" ControlToValidate="Width" CssClass="text-danger" Text="Width must be a decimal" ValidationExpression="\d+\.?\d*" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("width") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Height (inches)" SortExpression="height">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Height" runat="server" Text='<%# Bind("height") %>' Columns="8" MaxLength="8"></asp:TextBox>
                                            <asp:RegularExpressionValidator ID="heightRegex" runat="server" ControlToValidate="Height" CssClass="text-danger" Text="Height must be a decimal" ValidationExpression="\d+\.?\d*" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("height") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Max Weight (lbs)" SortExpression="maxWeight">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="MaxWeight" runat="server" Text='<%# Bind("maxWeight") %>' Columns="8" MaxLength="8"></asp:TextBox>
                                            <asp:RegularExpressionValidator ID="maxWeightRegex" runat="server" ControlToValidate="MaxWeight" CssClass="text-danger" Text="Max Weight must be a decimal" ValidationExpression="\d+\.?\d*" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("maxWeight") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Fuel Tank Size (gallons)" SortExpression="fuelTankSize">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="FuelTankSize" runat="server" Text='<%# Bind("fuelTankSize") %>' Columns="8" MaxLength="8"></asp:TextBox>
                                            <asp:RegularExpressionValidator ID="fuelTankRegex" runat="server" ControlToValidate="FuelTankSize" CssClass="text-danger" Text="Fuel Tank Size must be a decimal" ValidationExpression="\d+\.?\d*" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label5" runat="server" Text='<%# Bind("fuelTankSize") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Model" SortExpression="modelName">
                                        <EditItemTemplate>
                                            <asp:DropDownList runat="server" ID="Model" Width="150px" CssClass="form-control" AppendDataBoundItems="true" DataSourceID="SqlDataSource2" DataTextField="ModelName" DataValueField="ModelName" SelectedValue='<%#Bind("modelName")%>'>
                                            </asp:DropDownList>
                                            <asp:SqlDataSource runat="server" ID="SqlDataSource2" ConnectionString='<%$ ConnectionStrings:GoodsDeliveryConnectionString %>' SelectCommand="SELECT * FROM [TruckModels] ORDER BY [ModelName]"></asp:SqlDataSource>
                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="Model"
                                                CssClass="text-danger" ErrorMessage="This field is required" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="lblModel" runat="server" Text='<%# Bind("modelName") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Odometer (miles)" SortExpression="odometerReading">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Odometer" runat="server" Text='<%# Bind("odometerReading") %>' Columns="8" MaxLength="8"></asp:TextBox>
                                            <asp:RegularExpressionValidator ID="odometerRegex" runat="server" ControlToValidate="Odometer" CssClass="text-danger" Text="Odometer must be a decimal" ValidationExpression="\d+\.?\d*" />
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label6" runat="server" Text='<%# Bind("odometerReading") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:BoundField DataField="remark" HeaderText="Remarks" SortExpression="remark" />
                                    <asp:TemplateField HeaderText="Local Truck?" SortExpression="LocalTruck">
                                        <ItemTemplate>
                                            <asp:CheckBox ID="Local" runat="server" Checked='<%# Eval("LocalTruck") %>' Enabled="false" />
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:CheckBox ID="Local" runat="server" Checked='<%# Bind("LocalTruck") %>' />
                                        </EditItemTemplate>
                                        <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                    </asp:TemplateField>
                                </Columns>
                            </asp:GridView>
                            <asp:SqlDataSource ID="gdsDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:GoodsDeliveryConnectionString %>" DeleteCommand="TruckDelete" DeleteCommandType="StoredProcedure" SelectCommand="TruckSearch" SelectCommandType="StoredProcedure" UpdateCommand="TruckUpdate" UpdateCommandType="StoredProcedure">
                                <SelectParameters>
                                    <asp:ControlParameter ControlID="Search" Name="searchString" Type="String" ConvertEmptyStringToNull="false" />
                                </SelectParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="truckId" Type="Int32" />
                                    <asp:Parameter Name="licensePlateNum" Type="String" />
                                    <asp:Parameter Name="licensePlateState" Type="String" />
                                    <asp:Parameter Name="length" Type="double" />
                                    <asp:Parameter Name="width" Type="double" />
                                    <asp:Parameter Name="height" Type="double" />
                                    <asp:Parameter Name="maxWeight" Type="double" />
                                    <asp:Parameter Name="modelName" Type="String" />
                                    <asp:Parameter Name="fuelTankSize" Type="double" />
                                    <asp:Parameter Name="odometerReading" Type="double" />
                                    <asp:Parameter Name="remark" Type="String" />
                                </UpdateParameters>
                                <DeleteParameters>
                                    <asp:Parameter Name="truckId" Type="Int32" />
                                </DeleteParameters>
                            </asp:SqlDataSource>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</asp:Content>
